# Generated by Django 6.0.2 on 2026-02-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='is_exception',
            field=models.BooleanField(default=False),
        ),
    ]
