# Generated by Django 6.0.2 on 2026-03-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
