# Generated by Django 6.0.2 on 2026-02-26 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_reschedulehistory_availability_doctorexception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['start_time']},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='check_in_time',
            new_name='check_in_at',
        ),
        migrations.RenameField(
            model_name='reschedulehistory',
            old_name='changed_by',
            new_name='changed_by_user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='is_exception',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorexception',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('doctor', 'start_time'), name='unique_doctor_slot'),
        ),
    ]
