<<<<<<< HEAD
# Generated by Django 4.2.28 on 2026-03-03 22:01
=======
# Generated by Django 4.2.28 on 2026-03-02 02:23
>>>>>>> eb32374 (add queue)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointment_unique_slot'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='appointments.appointment'),
        ),
    ]
