# Generated by Django 4.2.28 on 2026-02-27 18:52

from django.db import migrations

def create_clinic_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Group.objects.get_or_create(name="Patient")
    Group.objects.get_or_create(name="Doctor")
    Group.objects.get_or_create(name="Receptionist")
    Group.objects.get_or_create(name="Admin")

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_clinic_groups),
    ]

