# Generated by Django 4.2.28 on 2026-03-03 22:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userapp',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='userapp',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
