# Generated by Django 4.2.28 on 2026-02-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20260227_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='session_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
