# Generated by Django 4.2.28 on 2026-02-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'requested'), ('confirmed', 'confirmed'), ('checked_in', 'checked_in'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('no_show', 'no_show')], default='requested', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
