# Generated by Django 6.0.2 on 2026-02-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_slot',
        ),
    ]
