# Generated by Django 6.0.2 on 2026-03-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_check_in_at_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_slot',
        ),
    ]
