"""
Django settings for clinic project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x^dd5sg&3j0k)*hztsk4l1hq$w&ju)i_^k&ewup@pdufh*q270'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'debug_toolbar',
    'accounts.apps.AccountsConfig',
    'appointments.apps.AppointmentsConfig',
    'dashboard.apps.DashboardConfig',
    'medical.apps.MedicalConfig',
    'scheduling.apps.SchedulingConfig',
    'django_email_verification',
    # 'scheduling'
]

MIDDLEWARE = [
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # "debug_toolbar.middleware.DebugToolbarMiddleware",
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clinic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clinic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'clinic_db',
        'USER': 'postgres',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.UserApp'

# Email Configuration (Gmail SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'somaya.ayman.elsayed@gmail.com'  
EMAIL_HOST_PASSWORD = "cfxx rwau yfva fpep" 
DEFAULT_FROM_EMAIL = 'somaya.ayman.elsayed@gmail.com'  

# django-email-verification Configuration
EMAIL_FROM_ADDRESS = DEFAULT_FROM_EMAIL
EMAIL_PAGE_DOMAIN = 'http://localhost:8000/'

# Email Verification Settings 
def email_verified_callback(user):
    user.is_active = True

# Signup Email Verification
EMAIL_MAIL_SUBJECT = 'Verify it\'s you {{ user.username }}'
EMAIL_MAIL_HTML = 'registration/emails/verify_email.html'
EMAIL_MAIL_PLAIN = 'registration/emails/verify_email.txt'
EMAIL_MAIL_TOKEN_LIFE = 60 * 60  
EMAIL_MAIL_PAGE_TEMPLATE = 'registration/emails/verification_success.html'
EMAIL_MAIL_CALLBACK = email_verified_callback

# Token expiration (in seconds) - 24 hours
PASSWORD_RESET_TIMEOUT = 86400

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # only if you have global static folder
]